# config for mrcupp-project circleci
version: 2.1
orbs:
  slack: circleci/slack@4.4.2
jobs:
  build-x86:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "Circle Tag: $CIRCLE_TAG"
            echo "Circle Sha1: $CIRCLE_SHA1"

            if [ -n "$CIRCLE_TAG" ]; then 
              echo "Found CIRCLE_TAG env var! Using CIRCLE_TAG for BUILD_TAG"
              echo 'export $BUILD_TAG=$CIRCLE_TAG' 
              echo 'export $BUILD_TAG=$CIRCLE_TAG' >> $BASH_ENV 
            else
              echo "Could not find CIRCLE_TAG env var! Using SHA1 for BUILD_TAG"
              echo 'export $BUILD_TAG=$CIRCLE_SHA1' 
              echo 'export $BUILD_TAG=$CIRCLE_SHA1' >> $BASH_ENV
            fi
            
            source $BASH_ENV
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Build Started - x86_64 image"
                  },
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by*: $CIRCLE_USERNAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH" 
                    }
                  ]
                }
              ]
            }
          event: always
      - checkout
      - run:
          name: Log in to github container repo (ghcr.io)
          command: |
            docker login ghcr.io -u iammrcupp -p $GITHUB_TOKEN
      - deploy:
          name: "Build and upload x86_64 image"
          command: |
            docker build -t ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:x86_64-${BUILD_TAG} .
            docker push ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:x86_64-${BUILD_TAG}
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
  build-arm64:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: arm.medium
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "Circle Tag: $CIRCLE_TAG"
            echo "Circle Sha1: $CIRCLE_SHA1"

            if [ -n "$CIRCLE_TAG" ]; then 
              echo "Found CIRCLE_TAG env var! Using CIRCLE_TAG for BUILD_TAG"
              echo 'export $BUILD_TAG=$CIRCLE_TAG' 
              echo 'export $BUILD_TAG=$CIRCLE_TAG' >> $BASH_ENV 
            else
              echo "Could not find CIRCLE_TAG env var! Using SHA1 for BUILD_TAG"
              echo 'export $BUILD_TAG=$CIRCLE_SHA1' 
              echo 'export $BUILD_TAG=$CIRCLE_SHA1' >> $BASH_ENV
            fi
            
            source $BASH_ENV
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Build Started - arm64 image"
                  },
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by*: $CIRCLE_USERNAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH" 
                    }
                  ]
                }
              ]
            }
          event: always
      - checkout
      - run:
          name: Log in to github container repo (ghcr.io)
          command: |
            docker login ghcr.io -u iammrcupp -p $GITHUB_TOKEN
      - deploy:
          name: "Build and upload arm64 image"
          command: |
            docker build -t ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:arm64-${BUILD_TAG} .
            docker push ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:arm64-${BUILD_TAG}
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
  upload-manifest:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "Circle Tag: $CIRCLE_TAG"
            echo "Circle Sha1: $CIRCLE_SHA1"

            if [ -n "$CIRCLE_TAG" ]; then 
              echo "Found CIRCLE_TAG env var! Using CIRCLE_TAG for BUILD_TAG"
              echo 'export $BUILD_TAG=$CIRCLE_TAG' 
              echo 'export $BUILD_TAG=$CIRCLE_TAG' >> $BASH_ENV 
            else
              echo "Could not find CIRCLE_TAG env var! Using SHA1 for BUILD_TAG"
              echo 'export $BUILD_TAG=$CIRCLE_SHA1' 
              echo 'export $BUILD_TAG=$CIRCLE_SHA1' >> $BASH_ENV
            fi
            
            source $BASH_ENV
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Build Started - multiarch image creation"
                  },
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by*: $CIRCLE_USERNAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH" 
                    }
                  ]
                }
              ]
            }
          event: always
      - checkout
      - run:
          name: Log in to github container repo (ghcr.io)
          command: |
            docker login ghcr.io -u iammrcupp -p $GITHUB_TOKEN
      - deploy:
          name: "Build and upload multiarch manifest for image"
          command: |
            set -eu
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker manifest create ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:${BUILD_TAG} ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:x86_64-${BUILD_TAG} ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:arm64-${BUILD_TAG}
            docker manifest push ghcr.io/iammrcupp/${CIRCLE_PROJECT_REPONAME}:${BUILD_TAG}
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1



workflows:
  version: 2
  build:
    jobs:
      - build-arm64:
          context:
            - docker-env
            - slack
            - github
      - build-x86:
          context:
            - docker-env
            - slack
            - github
      - upload-manifest:
          context:
            - docker-env
            - slack
            - github
          requires:
            - build-arm64
            - build-x86