# config for mrcupp-project circleci
version: 2.1
orbs:
  slack: circleci/slack@4.4.2
jobs:
  build-x86:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Build Started - x86_64 image"
                  },
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by*: $CIRCLE_USERNAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH" 
                    }
                  ]
                }
              ]
            }
          event: always
      - checkout
      - deploy:
          name: "Build and upload x86_64 image"
          command: |
            docker build -t ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:x86_64-${CIRCLE_SHA1} .
            docker push ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:x86_64-${CIRCLE_SHA1}
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
  build-arm64:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: arm.medium
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Build Started - arm64 image"
                  },
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by*: $CIRCLE_USERNAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH" 
                    }
                  ]
                }
              ]
            }
          event: always
      - checkout
      - deploy:
          name: "Build and upload arm64 image"
          command: |
            docker build -t ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:arm64-${CIRCLE_SHA1} .
            docker push ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:arm64-${CIRCLE_SHA1}
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
  upload-manifest:
    docker:
      - image: cimg/python:3.8.2
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Build Started - multiarch image creation"
                  },
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered by*: $CIRCLE_USERNAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME" 
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH" 
                    }
                  ]
                }
              ]
            }
          event: always
      - checkout
      - deploy:
          name: "Build and upload multiarch manifest for image"
          command: |
            set -eu
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker manifest create ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:x86_64-${CIRCLE_SHA1} ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:arm64-${CIRCLE_SHA1}
            docker push ghcr.io/${CIRCLECI_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  version: 2
  build:
    jobs:
      - build-arm64:
          context:
            - docker-env
            - slack
            - github
      - build-x86:
          context:
            - docker-env
            - slack
            - github
      - upload-manifest:
          context:
            - docker-env
            - slack
            - github
          requires:
            - build-arm64
            - build-x86